server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:mem:employee
    driverClassName: org.h2.Driver
    username: jalenhairston
    password: Idrinkdat12!
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
